SET (CPM_DOWNLOAD_VERSION 0.35.1)

FUNCTION (CPMGH REPO HASH)
    CPMADDPACKAGE ("https://github.com/${REPO}/archive/${HASH}.tar.gz")
ENDFUNCTION ()

IF (CPM_SOURCE_CACHE)
    GET_FILENAME_COMPONENT (CPM_SOURCE_CACHE ${CPM_SOURCE_CACHE} ABSOLUTE)
    SET (CPM_DOWNLOAD_LOCATION
         "${CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
ELSEIF (DEFINED ENV{CPM_SOURCE_CACHE})
    SET (CPM_DOWNLOAD_LOCATION
         "$ENV{CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
ELSE ()
    SET (CPM_DOWNLOAD_LOCATION
         "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
ENDIF ()

IF (NOT (EXISTS ${CPM_DOWNLOAD_LOCATION}))
    MESSAGE (STATUS "Downloading CPM.cmake to ${CPM_DOWNLOAD_LOCATION}")
    FILE (
        DOWNLOAD
        https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake
        ${CPM_DOWNLOAD_LOCATION})
ENDIF ()

INCLUDE (${CPM_DOWNLOAD_LOCATION})
